# Generated by Django 4.1.2 on 2022-11-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
    ]
