# Generated by Django 4.1.2 on 2022-11-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
